In [19]:
#Exercice 1

import numpy as np
import collections

A = np.arange(0,100,3)
   # [ i for i in range(0, 100) if i % 3 == 0 ]
    
B = np.sin((A**2)*(np.pi/2))
print(b)

C = np.amax(B)
print(C)

print(np.count_nonzero(B == 1))

-9.797174393178826e-16
1.0
17


In [33]:
#Exercice 2
M = np.eye(10)
def est_diagonal(M):
    return True if (M == np.triu(np.tril(M))).all() else False

def est_triangulaire_sup(M):
    return True if (M == np.tril(M)).all() else False

print(est_diagonal(M))
print(est_triangulaire_sup(M))
print(M)

True
True
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [128]:
#Exercice 3
import numpy as np

M = np.ones((8,8))
M[0:-1, 1:-1] = 0


N = []
for x in range(0, 8):
    N.append([0] * 8)
    for y in range (0,8):
        if x >= 7 or y == 0 or y == 7:
            N[x][y] = 1    
N

[[1, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 1],
 [1, 1, 1, 1, 1, 1, 1, 1]]

In [113]:
#Exercice 4
import time
import numpy as np

a = 0
b = 0
tmps1=time.time()
while a <= 1000000:
    b = a + b
    a = a+1
    
    
tmps2=time.time()-tmps1
print(b)
print ("Temps d'execution = %f" %tmps2)


tmps3=time.time()
c = np.arange(1000001)
d = c.sum(dtype=np.int64)
print(d)
tmps4=time.time()-tmps3
print ("Temps d'execution = %f \n\nMa methode est donc plus lente" %tmps4)

500000500000
Temps d'execution = 0.192486
500000500000
Temps d'execution = 0.004025 

Ma methode est donc plus lente


In [3]:
#Exercice 5
import numpy as np
A = np.random.rand(50,50)

max = 0
for i in range(49):
    for j in range(49):
        if max < A[j+1][i]-A[i][j]:
            max = A[i][j]
print(max)
    

0.7448487329763355


In [176]:
#Exercice 6
import numpy as np
a = np.random.rand(50,50)

count=np.count_nonzero(a<=0.5)
print(count)

result=(a>0.5).astype(int)
print(result)

result2=np.where(a<0.5,0,1)
print(result2)

1232
[[0 0 1 ... 1 1 0]
 [0 1 0 ... 0 1 1]
 [1 1 0 ... 1 0 0]
 ...
 [1 0 1 ... 1 0 1]
 [1 1 0 ... 1 1 1]
 [0 1 1 ... 0 1 0]]
[[0 0 1 ... 1 1 0]
 [0 1 0 ... 0 1 1]
 [1 1 0 ... 1 0 0]
 ...
 [1 0 1 ... 1 0 1]
 [1 1 0 ... 1 1 1]
 [0 1 1 ... 0 1 0]]


In [110]:
#Exercice 7
import numpy as np

a = np.array([[1,2,1,1],[0,1,2,1],[1,0,1,2],[2,1,0,1]])
b = np.array([0,0,1,0])

print(np.linalg.det(a))

result=np.linalg.solve(a,b)
print(result)

result2=np.dot(a,result)
print(result2)

-4.0
[-0.5  0.  -0.5  1. ]
[0. 0. 1. 0.]


In [109]:
#Exercice 8

def encode(input_string):
    count = 1
    tmp = ''
    lst = ''
    for character in input_string:
        if character != tmp:
            if tmp:
                entry = str(count) + tmp 
                lst = lst + entry
            count = 1
            tmp = character
        else:
            count += 1
    else:
        try:
            entry = str(count) + character 
            lst = lst + entry
            return (lst, 0)
        except Exception as e:
            print("Tu t trom P 2 txt".format(e=e)) 
            return (e, 1)
 

def decode(lst):
    result = ''
    tmp = []
    for i in range (0, int(len(lst)/2)):
        tmp.append(lst[2*i:2*i+2])
        result = result + (int(tmp[i][0]) * (tmp[i][1]))
    return result
        
        


value = encode(str(input('Entrer votre texte \n')))
if value[1] == 0:
    print('Code : ' + format(value[0]))  
    print('Decode :' + decode(value[0]))

Entrer votre texte 
ffffdddddffff
Code : 4f5d4f
Decode :ffffdddddffff
